"""Add AI analysis fields and email relationships

Revision ID: 1a40ea25c893
Revises: 9c91270c5bb1
Create Date: 2024-10-28 14:04:00.534174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a40ea25c893'
down_revision = '9c91270c5bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_analysis_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ai_model_used', sa.String(length=50), nullable=True))

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_ai_generated', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'emails', ['email_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_ai_generated', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'emails', ['email_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_ai_generated')
        batch_op.drop_column('email_id')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_ai_generated')
        batch_op.drop_column('email_id')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('ai_model_used')
        batch_op.drop_column('ai_analysis_date')
        batch_op.drop_column('ai_analysis')

    # ### end Alembic commands ###
