"""Add EmailFetchTracker model

Revision ID: f66935b4237f
Revises: 
Create Date: 2024-11-25 20:02:29.852788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66935b4237f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('change_metadata', sa.JSON(), nullable=True),
    sa.Column('is_risky', sa.Boolean(), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rollback_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_change_id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('rollback_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['system_change_id'], ['system_changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unknown_emails', schema=None) as batch_op:
        batch_op.alter_column('is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unknown_emails', schema=None) as batch_op:
        batch_op.alter_column('is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.drop_table('rollback_history')
    op.drop_table('system_changes')
    # ### end Alembic commands ###
